engines:
  rubocop:
    enabled: true
    channel: rubocop-0-54

ratings:
   paths:
   - "lib/**/*"
   - "**.rb"

exclude_patterns:
  - 'docs/'
  # These are the defaults that need to be re-applied because I need a custom choice.
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
