sudo: false
language: ruby
cache: bundler

env:
  global:
    # Github oauth key to allow getting the rails-head gemfile
    - secure: "OMVXtjv1t4dqxAa9wbeOwFRkMtln3WpHIrocie8bHxeiPjpMcqcYOBA9gljaOCPTKPN89ROuyGkSx0qcjvt2iQePC9wAcZRNjTFppgJdPGwpCqz633mSoryp5md20oXxx81rDzcg9Rzfw47/OxmdwqL6hI9OjjipfsQZOBcF5Yi9UU5Ng56w0MaKbzfevkm4s2/SB8fm7fObJhL/skQDAmoscdfm+pz/0On10kQx0b4AEPAXl8p3bVE+PR2/m9V6LwYeQ7VvOlsJGQVnlBO9LV/QPcFS2+CvSCs/nW+XLS1ItMom6h3OaiEjLi1xo/d+AcvNnkJWSI3p80EDpoBT7DI/lyMWJr/LgyzbUSHqMNwflOGdHWZHd8ihsgefLo8wU1p4+lVQisu0oCm+KgdZwkVOghw1XLn5sKR7Tzhj0jAMc21/jeBoFppgJyhgb1QaijOl1xpuUML6rE9+u3StnJkU9mgARHzwbaR+vIRHz6KaBbbiD7Mu8sKkgYWgTQr8yN1TlOKo4okCwNZYjO9VsDrVGtp1CrS+vWAvOmmgAM0fV7ITEPnAwlB4mnUpJUxSuy3UOuhxcADkM3cYH6rk/7FDupRYQo3rO+NQUO7FavG0WYIzBHsL+X7gnb/3oslxHQbf4HjzrVPUj5ibw/5nbL/4iOhR0v4xMQ7T2IMQeMs="

_ruby_aliases:
  - &ru2_5 2.5.0
  - &ru2_4 2.4.1
  - &ru2_3 2.3.4
  - &ru2_2 2.2.7
  - &ru2_1 2.1.10

_rails_aliases:
  - &rails_head gemfiles/rails_head.gemfile
  - &rails_5_2 gemfiles/rails_5_2.gemfile
  - &rails_5_1 gemfiles/rails_5_1.gemfile
  - &rails_5_0 gemfiles/rails_5_0.gemfile
  - &rails_4_2 gemfiles/rails_4_2.gemfile
  - &rails_4_1 gemfiles/rails_4_1.gemfile

matrix:
  include:
    - gemfile: *rails_head
      rvm: ruby-head
    - gemfile: *rails_head
      rvm: *ru2_5

    - gemfile: *rails_5_2
      rvm: ruby-head
    - gemfile: *rails_5_2
      rvm: *ru2_5
    - gemfile: *rails_5_2
      rvm: *ru2_4
    - gemfile: *rails_5_2
      rvm: *ru2_3

    - gemfile: *rails_5_1
      rvm: *ru2_5
    - gemfile: *rails_5_1
      rvm: *ru2_4
    - gemfile: *rails_5_1
      rvm: *ru2_3
    - gemfile: *rails_5_1
      rvm: *ru2_2

    - gemfile: *rails_5_0
      rvm: *ru2_4
    - gemfile: *rails_5_0
      rvm: *ru2_3
    - gemfile: *rails_5_0
      rvm: *ru2_2

    - gemfile: *rails_4_2
      rvm: *ru2_4
    - gemfile: *rails_4_2
      rvm: *ru2_3
    - gemfile: *rails_4_2
      rvm: *ru2_2
    - gemfile: *rails_4_2
      rvm: *ru2_1

    - gemfile: *rails_4_1
      rvm: *ru2_3
    - gemfile: *rails_4_1
      rvm: *ru2_2
    - gemfile: *rails_4_1
      rvm: *ru2_1

  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile

  # fast_finish makes Travis send multiple notification email when things fail.
  # https://github.com/travis-ci/travis-ci/issues/1696
  # fast_finish: true

before_install: gem install bundler

before_script:
  - psql -c 'CREATE DATABASE activerecord_where_assoc' -U postgres
  - mysql -e 'CREATE DATABASE activerecord_where_assoc'

script:
  - DB=mysql bundle exec rake test
  - bundle exec rake test DB=pg
  - bundle exec rake test DB=sqlite3
  - bundle exec rake coveralls:push


